import type { Metadata } from 'next';
import './globals.css';
import { montserrat } from '@/utils/fonts';
import SessionProvider from '../../Providers/SessionProvider';
import { notFound } from 'next/navigation';
import { locales } from '@/constants/constants';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'react-loading-skeleton/dist/skeleton.css';
import 'react-toastify/dist/ReactToastify.css';
import Toast from '@/components/atoms/Toast';
import SocketProvider from '@/Providers/SocketProvider';
import SectionContext from '@/context/SectionContext';
import BottomBar from '@/components/molecules/BottomBar';
import React from 'react';
import { updateGlobalLocale } from '@/utils/Date';
import { useTranslations } from 'next-intl';
import NotificationContextWrapper from '@/context/NotificationContext';
import TaskContextWrapper from '@/context/TaskContext';

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export const metadata: Metadata = {
  title: 'Task Management App',
  description: 'Generated by create next app',
  viewport: `width=device-width, initial-scale=1.0`,
};

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  if (!locales.includes(locale as any)) notFound();
  updateGlobalLocale(locale);

  const t = useTranslations('BottomBar');
  const translations = {
    tabBottomHome: t('tabBottomHome'),
    tabBottomPlanning: t('tabBottomPlanning'),
    tabBottomStatistics: t('tabBottomStatistics'),
    tabBottomSettings: t('tabBottomSettings'),
  };

  return (
    <html lang={locale}>
      <SessionProvider>
        <NotificationContextWrapper>
          <TaskContextWrapper>
            <SocketProvider>
              <SectionContext>
                <body
                  className={`${montserrat.className} bg-taskBackground overflow-y-hidden max-h-screen  min-w-[1200px] max-w-[2000px]  mx-auto`}
                >
                  <Toast />
                  {children}
                  <div className='absolute top-0 w-full min-w-[1024px] max-w-[2000px] mx-auto z-50'>
                    <BottomBar translations={translations} />
                  </div>
                </body>
              </SectionContext>
            </SocketProvider>
          </TaskContextWrapper>
        </NotificationContextWrapper>
      </SessionProvider>
    </html>
  );
}
